services:
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - ./db/mysql:/var/lib/mysql
        ports:
            - 4242:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
