openapi: 3.0.3
info:
  title: 'API Documentation'
  description: 'Read information about API'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/decks:
    get:
      summary: ''
      operationId: getApiV1Decks
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiV1Decks
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: voluptas
                  nullable: false
              required:
                - title
      security: []
  /api/v1/decks/search:
    get:
      summary: ''
      operationId: getApiV1DecksSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/decks/{id}':
    get:
      summary: ''
      operationId: getApiV1DecksId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiV1DecksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: amet
                  nullable: false
              required:
                - title
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1DecksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the deck.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/decks/questions/search:
    get:
      summary: ''
      operationId: getApiV1DecksQuestionsSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/decks/{deck_id}/questions/{id}':
    get:
      summary: ''
      operationId: getApiV1DecksDeck_idQuestionsId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: deck_id
        description: 'The ID of the deck.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: id
        description: 'The ID of the question.'
        example: 13
        required: true
        schema:
          type: integer
  '/api/v1/decks/{deck_id}/questions':
    get:
      summary: ''
      operationId: getApiV1DecksDeck_idQuestions
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiV1DecksDeck_idQuestions
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                front:
                  type: string
                  description: ''
                  example: nobis
                  nullable: false
                back:
                  type: string
                  description: ''
                  example: maxime
                  nullable: false
                tags:
                  type: array
                  description: ''
                  example:
                    - dolorum
                  items:
                    type: string
              required:
                - front
                - back
      security: []
    parameters:
      -
        in: path
        name: deck_id
        description: 'The ID of the deck.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/decks/{deck_id}/questions/{questionId}':
    put:
      summary: ''
      operationId: putApiV1DecksDeck_idQuestionsQuestionId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                front:
                  type: string
                  description: ''
                  example: similique
                  nullable: false
                back:
                  type: string
                  description: ''
                  example: et
                  nullable: false
                deck_id:
                  type: integer
                  description: 'The <code>id</code> of an existing record in the decks table.'
                  example: 13
                  nullable: false
                tags:
                  type: array
                  description: ''
                  example:
                    - est
                  items:
                    type: string
              required:
                - front
                - back
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1DecksDeck_idQuestionsQuestionId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: deck_id
        description: 'The ID of the deck.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: questionId
        description: ''
        example: 11
        required: true
        schema:
          type: integer
  /api/v1/tags:
    get:
      summary: ''
      operationId: getApiV1Tags
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/decks/{deck_id}/questions/{question}/answer':
    post:
      summary: ''
      operationId: postApiV1DecksDeck_idQuestionsQuestionAnswer
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: ''
                  example: hard
                  nullable: false
                  enum:
                    - easy
                    - good
                    - hard
                    - again
              required:
                - type
      security: []
    parameters:
      -
        in: path
        name: deck_id
        description: 'The ID of the deck.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: question
        description: 'The question.'
        example: 13
        required: true
        schema:
          type: integer
  /api/v1/profile:
    put:
      summary: ''
      operationId: putApiV1Profile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: aut
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: wtorp@example.org
                  nullable: false
              required:
                - name
                - email
      security: []
  /api/v1/all/stats:
    get:
      summary: ''
      operationId: getApiV1AllStats
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
